# Generated by Django 2.2.4 on 2019-08-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
    ]
