# Generated by Django 2.2.4 on 2019-08-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0004_auto_20190805_1209'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
    ]
