# Generated by Django 2.2.4 on 2019-08-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0008_auto_20190807_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='user_s',
        ),
    ]
